language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - ./tests/install-extension.sh
  - phpenv config-rm xdebug.ini
  - composer update --dev
  - phpenv rehash

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=i18n app/
  - ZEND_DONT_UNLOAD_MODULES=1 $(phpenv which php) vendor/bin/phpunit --configuration tests/phpunit.xml --testsuite=all

after_failure:
  - sudo apt-get -qq install gdb
  - ./framework/tests/ci/failure.sh