language: php

before_install:
 - sudo apt-get update
 - sudo apt-get -qq install gdb

before_script:
  - ./tests/install-extension.sh
  - composer update --dev
  - phpenv rehash

php:
  - 5.4
  - 5.5
  - 5.6

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --ignore=i18n app/
  - gdb php -command=tests/phpunit