language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - yes '' | pecl -q install -f mongodb
  - ./tests/install-extension.sh
  - composer update
  - phpenv config-rm xdebug.ini
  - phpenv rehash

script:
  - php vendor/bin/phpcs --encoding=utf-8 --ignore=framework .
  - php vendor/bin/phpunit --testsuite=all

after_failure:
  - sudo apt-get -qq install gdb
  - gdb -quiet -command=framework/tests/ci/gdb --args $(phpenv which php) vendor/bin/phpunit --debug --colors --configuration tests/phpunit.xml --testsuite=all
